name: Scraper UVI

permissions:
  contents: write

on:
  schedule:
    - cron: "0 12 * * *" # 09:00 AR
    - cron: "0 13 * * *" # 10:00 AR
    - cron: "0 14 * * *" # 11:00 AR
  workflow_dispatch:

jobs:
  uvi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper UVI
        run: |
          python scrapers/scraper_uvi.py

      - name: Commit data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/uvi
          git commit -m "chore: update UVI" || echo "No changes"
          git push
